<?php
/**
 * @file
 * Code for the Walkthrough global feature.
 */

include_once 'walkthrough_global.features.inc';
/**
 * Implements hook_menu().
 */
function walkthrough_global_menu() {
  $items = array();

  $items['admin/config/services/walkthrough'] = array(
    'title' => 'Walkthrough configuration',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer walkthrough'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('walkthrough_global_configuration_form'),
    'file' => 'walkthrough_global.admin.inc'
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function walkthrough_global_permission() {
  return array(
    'administer walkthrough' => array(
      'title' => t('Administer walkthrough'),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function walkthrough_global_libraries_info() {
  $libraries['phpseclib'] = array(
    'name' => 'phpseclib',
    'vendor url' => 'http://phpseclib.sourceforge.net',
    'download url' => 'http://phpseclib.sourceforge.net',
    'version' => '2.1',
    'files' => array(
      'php' => array(
        'Crypt/RSA.php',
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_services_resources().
 */
function walkthrough_global_services_resources() {
  $resources = array();

  $resources['walkhub-user'] = array(
    'actions' => array(
      'registration' => array(
        'help' => 'Create a new user account.',
        'callback' => '_walkthrough_global_resource_registration',
        'args' => array(
          array(
            'name' => 'username',
            'type' => 'string',
            'description' => 'A valid username',
            'source' => array(
              'data' => 'username',
            ),
            'optional' => FALSE,
          ),
          array(
            'name' => 'mail',
            'type' => 'string',
            'description' => 'A valid e-mail',
            'source' => array(
              'data' => 'mail',
            ),
            'optional' => FALSE,
          ),
          array(
            'name' => 'password',
            'type' => 'string',
            'description' => 'A valid password',
            'source' => array(
              'data' => 'password',
            ),
            'optional' => FALSE,
          ),
          array(
            'name' => 'rsatoken',
            'type' => 'string',
            'description' => 'A valid token to filter out robots.',
            'source' => array(
              'data' => 'token',
            ),
            'optional' => FALSE,
          ),
        ),
        'access callback' => '_walkthrough_global_resource_registration_access',
        'access arguments append' => TRUE,
        'file' => array(
          'type' => 'inc',
          'module' => 'walkthrough_global',
          'name' => 'walkthrough_global.services',
        ),
      ),
    ),
  );

  return $resources;
}

/**
 *
 */
function _walkthrough_global_resource_registration_access() {
  if (($library = libraries_load("phpseclib")) && !empty($library['loaded'])) {
  }
}
