<?php
/**
 * @file
 */

/**
 *  Implements hook_node_presave().
 *
 * @param $node
 */
function walkthrough_parser_node_presave($node) {
  if ($node->type == 'walkthrough' && !empty($node->field_raw_input[LANGUAGE_NONE][0]['value']) && empty($node->nid)) {
    $source = field_get_items('node', $node, 'field_raw_input', LANGUAGE_NONE);
    $steps = _walkthrough_parser_break_up_to_steps($source[0]['value']);
    if (!empty($steps)) {
      // Delete the previously attached steps.
      $old_steps_nids = array();
      $old_steps = field_get_items('node', $node, 'field_steps', LANGUAGE_NONE);
      if (is_array($old_steps)) {
        foreach ($old_steps as $old_step) {
          $old_steps_nids[] = $old_step['target_id'];
        }
      }
      node_delete_multiple($old_steps_nids);

      // Create new nodes based on the selenium source.
      $walkthrough_steps = array();
      foreach ($steps as $key => $step) {
        $steps[$key]['node'] = _walkthrough_parser_create_step_node($step, $key, $node);
        $walkthrough_steps[$key]['target_id'] = $steps[$key]['node']->nid;
      }
      $node->field_steps[LANGUAGE_NONE] = $walkthrough_steps;
    }
  }
}

/**
 * Break up to steps $source selenium input.
 *
 * @param $source
 * @return array
 */
function _walkthrough_parser_break_up_to_steps($source) {
  $steps = array();
  $doc = new DOMDocument();
  // Load the selenium test case.
  $doc->loadHTML($source);
  $basexpath = new DOMXPath($doc);
  $baseList = $basexpath->query('//link[@rel="selenium.base"]');
  $base = $baseList->length ? $baseList->item(0)->getAttribute('href') : NULL;
  $xpath = new DOMXpath($doc);
  // Break up to steps.
  $elements = $xpath->query('//tbody/tr');
  if ($elements->length) {
    // Loop through the steps.
    foreach ($elements as $step => $element) {
      // Get the step attributes.
      $attributes = $element->getElementsByTagName('td');
      foreach ($attributes as $key => $attribute) {
        switch ($key) {
          case 0:
            $steps[$step]['action'] = $attribute->nodeValue;
            break;
          case 1:
            $steps[$step]['xpath'] = $attribute->nodeValue;
            break;
          case 2:
            $steps[$step]['description'] = $attribute->nodeValue;
            break;
        }
      }
      if ($steps[$step]['action'] === 'open') {
        $components = parse_url($steps[$step]['xpath']);
        if (empty($components['host'])) {
          $steps[$step]['xpath'] = $base . trim($steps[$step]['xpath'], '/');
        }
      }
    }
  }
  return $steps;
}

/**
 *
 *
 * @param $source
 * @return string
 */
function _walkthrough_parser_parse_url($source) {
  $url = NULL;
  $doc = new DOMDocument();
  // Load the selenium test case.
  $doc->loadHTML($source);
  $link = $doc->getElementsByTagName('link');
  $url = $link->item(0)->getAttribute('href');
  return $url;
}

/**
 * Create a step node.
 *
 * @param $step
 * @param $key
 * @return stdClass
 */
function _walkthrough_parser_create_step_node($step, $key, $walkthrough_node) {
  $node = new stdClass();
  $node->title = "$walkthrough_node->title $key. step";
  $node->type = 'step';
  $node->language = $walkthrough_node->language;
  node_object_prepare($node);

  $node->field_command_1[LANGUAGE_NONE][0] = array(
    'value' => $step['action'],
  );

  $node->field_command_2[LANGUAGE_NONE][0] = array(
    'value' => $step['xpath'],
  );

  $node->field_command_3[LANGUAGE_NONE][0] = array(
    'value' => $step['description'],
  );

  node_save($node);
  return $node;

}
