<?php
/**
 * @file
 * Code for the WalkHub feature.
 */

include_once 'walkhub.features.inc';

/**
 *  Implements hook_node_presave().
 */
function walkhub_node_presave($node) {
  if ($node->type == 'walkthrough' && !empty($node->field_raw_input[LANGUAGE_NONE][0]['value']) && empty($node->nid)) {
    $source = field_get_items('node', $node, 'field_raw_input', LANGUAGE_NONE);
    $steps = _walkhub_break_up_to_steps($source[0]['value']);
    if (!empty($steps)) {
      // Delete the previously attached steps.
      $old_steps_nids = array();
      $old_steps = field_get_items('node', $node, 'field_steps', LANGUAGE_NONE);
      if (is_array($old_steps)) {
        foreach ($old_steps as $old_step) {
          $old_steps_nids[] = $old_step['target_id'];
        }
      }
      node_delete_multiple($old_steps_nids);

      // Create new nodes based on the selenium source.
      $walkthrough_steps = array();
      foreach ($steps as $key => $step) {
        $steps[$key]['node'] = _walkhub_create_step_node($step, $key, $node);
        $walkthrough_steps[$key]['target_id'] = $steps[$key]['node']->nid;
      }
      $node->field_steps[LANGUAGE_NONE] = $walkthrough_steps;
    }
  }
}

/**
 * Break up to steps $source selenium input.
 *
 * @param $source
 * @return array
 */
function _walkhub_break_up_to_steps($source) {
  static $highlightdata = array(
    'addSelection' => 0,
    'assignId' => 0,
    'check' => 0,
    'click' => 0,
    'clickAt' => 0,
    'contextMenu' => 0,
    'contextMenuAt' => 0,
    'doubleClick' => 0,
    'doubleClickAt' => 0,
    'dragAndDrop' => 0,
    'dragAndDropToObject' => 0,
    'dragdrop' => 0,
    'fireEvent' => 0,
    'focus' => 0,
    'highlight' => 0,
    'keyDown' => 0,
    'keyPress' => 0,
    'keyUp' => 0,
    'mouseDown' => 0,
    'mouseDownAt' => 0,
    'mouseDownRight' => 0,
    'mouseDownRightAt' => 0,
    'mouseMove' => 0,
    'mouseMoveAt' => 0,
    'mouseOut' => 0,
    'mouseOutAt' => 0,
    'mouseOver' => 0,
    'mouseUp' => 0,
    'mouseUpAt' => 0,
    'mouseUpRight' => 0,
    'mouseUpRightAt' => 0,
    'removeAllSelections' => 0,
    'removeSelection' => 0,
    'select' => 0,
    'selectFrame' => 0,
    'setCursorPosition' => 0,
    'submit' => 0,
    'type' => 0,
    'typeKeys' => 0,
    'uncheck' => 0,
  );

  $steps = array();
  $doc = new DOMDocument();
  // Load the selenium test case.
  $doc->loadHTML($source);
  $basexpath = new DOMXPath($doc);
  $baseList = $basexpath->query('//link[@rel="selenium.base"]');
  $base = $baseList->length ? $baseList->item(0)->getAttribute('href') : NULL;
  $xpath = new DOMXpath($doc);
  // Break up to steps.
  $elements = $xpath->query('//tbody/tr');
  if ($elements->length) {
    // Loop through the steps.
    foreach ($elements as $step => $element) {
      // Get the step attributes.
      $attributes = $element->getElementsByTagName('td');
      foreach ($attributes as $key => $attribute) {
        switch ($key) {
          case 0:
            $steps[$step]['action'] = $attribute->nodeValue;
            break;
          case 1:
            $steps[$step]['xpath'] = $attribute->nodeValue;
            break;
          case 2:
            $steps[$step]['description'] = $attribute->nodeValue;
            break;
        }
      }
      $act = endsWith($steps[$step]['action'], 'AndWait') ?
        substr($steps[$step]['action'], 0, -7) : $steps[$step]['action'];
      $steps[$step]['highlight'] = isset($highlightdata[$act]) ?
        ($highlightdata[$act] ? $steps[$step]['description'] : $steps[$step]['xpath']) : '';
      if ($steps[$step]['action'] === 'open') {
        $components = parse_url($steps[$step]['xpath']);
        if (empty($components['host'])) {
          $steps[$step]['xpath'] = $base . trim($steps[$step]['xpath'], '/');
        }
      }
    }
  }
  return $steps;
}

function endsWith($haystack, $needle) {
  return substr($haystack, -strlen($needle)) == $needle;
}

/**
 *
 *
 * @param $source
 * @return string
 */
function _walkhub_parse_url($source) {
  $doc = new DOMDocument();
  // Load the selenium test case.
  $doc->loadHTML($source);
  $link = $doc->getElementsByTagName('link');
  $url = $link->item(0)->getAttribute('href');
  return $url;
}

/**
 * Create a step node.
 *
 * @param $step
 * @param $key
 * @return stdClass
 */
function _walkhub_create_step_node($step, $key, $walkthrough_node) {
  $node = new stdClass();
  $node->title = "$walkthrough_node->title $key. step";
  $node->type = 'step';
  $node->language = $walkthrough_node->language;
  node_object_prepare($node);

  $node->field_command_1[LANGUAGE_NONE][0] = array(
    'value' => $step['action'],
  );

  $node->field_command_2[LANGUAGE_NONE][0] = array(
    'value' => $step['xpath'],
  );

  $node->field_command_3[LANGUAGE_NONE][0] = array(
    'value' => $step['description'],
  );

  $node->field_step_highlight[LANGUAGE_NONE][0] = array(
    'value' => $step['highlight'],
  );

  node_save($node);
  return $node;
}
