<?php
/**
 * @file
 * Code for the Walkhub comments feature.
 */

include_once 'walkhub_comments.features.inc';

function walkhub_comments_form_alter(&$form, &$form_state, $form_id) {

  var_dump($form_id);

  if ($form_id === 'comment_node_walkthrough_form') {

    //dpm($form);
    $form['field_related_step']['#access'] = FALSE;
//    if (coffe_points_access() == FALSE) {
//      hide($form['account']['roles']);
//      hide($form['account']['status']);
//      hide($form['account']['signature_settings']);
//      $form['field_loyality']['#access'] = FALSE;
//    }
  }
}