<?php
/**
 * Implements hook_token_info().
 */
function walkhub_tcard_token_info() {
  $info['tokens']['node']['wt_twitter_screenshot'] = array (
    'name' => t('Walkthrough Twitter Card image'),
    'description' => t('The image to show on twitter card.')
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function walkhub_tcard_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  if ($type == 'node') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'wt_twitter_screenshot':
          $image = '';
          $walkthrough_loaded = $data['node'];

          if ($screening_loaded = walkthrough_get_latest_screening_from_walkthrough($walkthrough_loaded)) {
            $screenshots = _walkthrough_slideshow_get_screenshots_in_order($screening_loaded);
            if (isset($screenshots[1]['uri'])) {
              $image = image_style_url('twitter_image_style', $screenshots[1]['uri']);
            }
          }

          if (!$image) {
            $theme_path = drupal_get_path('theme', 'walkhub_theme');
            $image = url("{$theme_path}/images/walkhub-logo-light.jpg", array('absolute' => TRUE));
          }

          $replacements[$original] = $image;
          break;
      }
    }
  }
  return $replacements;
}
