<?php
/**
 * Back-end logic implementation for the screening queue feature.
 */


/**
 * Implements hook_permission():
 */
function walkhub_screening_queue_permission() {
  return array(
    'mark any content for screening' => array(
      'title' => t('Mark any content for screening'),
    ),
    'mark own content for screening' => array(
      'title' => t('Mark own content for screening'),
    ),
  );
}

/**
 * Implements hook_flag_access().
 */
function walkhub_screening_queue_flag_access($flag, $entity_id, $action, $account) {
   // Load the mark for screening flag by machine name.
  $mark_for_screening = flag_get_flag('mark_for_screening');

  if (!empty($mark_for_screening) && $flag->fid == $mark_for_screening->fid) {
    // Check that the current user has access to mark any content for screening.
    if (user_access('mark any content for screening', $account)) {
      return TRUE;
    }

    // Check that the current user has access to mark any content for screening.
    $entity = entity_load($flag->entity_type, array($entity_id));
    if (reset($entity)->uid == $account->uid && user_access('mark own content for screening', $account)) {
      return TRUE;
    }

    return FALSE;
  }
}

/**
 * Implements hook_flag_flag().
 */
function walkhub_screening_queue_flag_flag($flag, $entity_id, $account, $flagging) {
   // Load the mark for screening flag by machine name.
  $mark_for_screening = flag_get_flag('mark_for_screening');

  if (!empty($mark_for_screening) && $flag->fid == $mark_for_screening->fid) {
    global $user;
    // Update the mark for screening flag marked by user reference field.
    $flagging->field_marked_by[LANGUAGE_NONE][0]['target_id'] = $user->uid;
    field_attach_update('flagging', $flagging);
  }
}

/**
 * Implements hook_flag_unflag().
 */
function walkhub_screening_queue_flag_unflag($flag, $entity_id, $account, $flagging) {
   // Load the mark for screening flag by machine name.
  $mark_for_screening = flag_get_flag('mark_for_screening');

  if (!empty($mark_for_screening) && $flag->fid == $mark_for_screening->fid) {
    // Unset the mark for screening flag marked by user reference field.
    unset($flagging->field_marked_by);
    field_attach_update('flagging', $flagging);
  }
}

/**
 * Implements hook_services_resources().
 */
function walkhub_screening_queue_services_resources() {
  $resources = array();

  $resources['walkhub-walkthrough-screening-queue'] = array(
    'index' => array(
      'callback' => '_walkhub_screening_queue_get_queue',
      'file' => array(
        'type' => 'inc',
        'module' => 'walkhub_screening_queue',
        'name' => 'walkhub_screening_queue.services'
      ),
      'access arguments' => array('access content'),
      'args' => array(),
    ),
  );

  return $resources;
}
